import { Inter } from "next/font/google";
import "./globals.css";
import FilterProvider from "@/provider/CartProvider";
import CartProvider from "@/provider/CartProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <FilterProvider>{children}</FilterProvider>
        </CartProvider>
      </body>
    </html>
  );
}
